version: '2.1'
services: 
  stream-board-proxy:
    image: lacardenasv/2e_stream-board_proxy
    depends_on:
      - stream-board-api
      - authentication-ms
      - chat-ms
      - board-ms
    ports:
      - "80:80"
  stream-board-api:
    image: lacardenasv/2e_streamboard_api
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTHENTICATION_PORT: '4003'
      AUTHENTICATION_ENTRY: 'auth'
      AUTHENTICATION_ENTRY1: 'users'
      AUTH_PORT: '4003'
      AUTH_ENTRY: 'ldap/'
      BOARD_PORT: '4002'
      BOARD_ENTRY: 'api'
      CHAT_PORT: '4004'
      CHAT_ENTRY: 'chat-room'
      ROOMS_PORT: '4001'
      ROOMS_ENTRY: 'rooms'
    ports:
      - "5000:5000"
    depends_on:
      - stream-board-subscriptions-socket-server
  stream-board-subscriptions-socket-server:
    image: afelipega/2e_subscriptions_socket_server
    ports:
      - "5555:3000"
  authentication-db:
    image: mysql:5.7.22
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: arqui
      MYSQL_USER: user
      MYSQL_PASSWORD: arqui
      MYSQL_DATABASE: authentication-db
      MYSQL_HOST: authentication-db
  authentication-ms:
    image: lacardenasv/2e_authentication_ms
    command:  bash -c "sleep 240 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4003 -b '0.0.0.0'"
    environment:
      PORT: '4003'
    depends_on:
      - authentication-db
    ports:
      - "4003:4003"
  rooms-db:
    image: mysql:5.7.22
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: roomsUser
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: rooms
      MYSQL_HOST: rooms-db
  rooms-ms:
    image: lacardenasv/2e_room_ms
    command: run main.go
    environment:
      PORT: '4001'
    depends_on:
      - rooms-db
    ports:
      - "4001:4001"
  chat-db-1:
    image: redis:latest
  chat-db:
    image: mysql:5.7.22
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: chatStreamBoard
      MYSQL_USER: user
      MYSQL_PASSWORD: chatStreamBoard
      MYSQL_DATABASE: chat_ms_development
      MYSQL_HOST: chat-db
  chat-ms:
    image: lacardenasv/2e_chat_ms
    command: bash -c "python3.6 manage.py runserver 0.0.0.0:4004"
    environment: 
      PORT: '4004'
    #TODO: Delete
    ports:
      - '4004:4004'
    depends_on:
      - chat-db-1
      - chat-db
  board-db:
    image: redis:latest
  board-ms:
    image: lacardenasv/2e_board_ms
    environment: 
      PORT: '4002'
    #TODO: Delete
    ports:
      - '4002:4002'
    depends_on:
      - board-db
  streaming-ms:
    image: lacardenasv/2e_video_streaming_ms
    environment:
      PORT: '4005'
    #TODO: Delete
    ports:
      - '4005:4005'
  streamboard-ldap:
    image: osixia/openldap:1.1.8
    container_name: streamboard-ldap
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Software Architecture"
      LDAP_DOMAIN: "arqsoft.unal.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "arqsoft.org"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "streamboard-ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    links:
      - streamboard-ldap
